### ISSUE TITLE
How to combine frontend with backend of your repo in my system

### ISSUE THREAD

**Issue by JayantDwivedi** [rushilp2311/bug-trackr#3]
Please provide a step by step guide to setup both frontend and backend in my pc

**Comment by rushilp2311** [comment]
Hi @JayantDwivedi, If you check the Readme of this project you can see the link to the code for the backend. 
In order to install and run both the backend and the frontend. You need to clone both the repositories and then you need to open both folders in separate terminals and run `yarn`. After the installation is done you can just type `yarn start` in both terminals and it should run the frontend on localhost:3000 and backend on localhost:3001. 
But for both the commands to run successfully you need to install yarn first. You can check this link https://yarnpkg.com/getting-started/install if you don't have yarn installed.

NOTE: You need to have MongoDB installed on your local machine.
